# Generated by Django 2.2.9 on 2021-01-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myswsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devtool',
            options={'get_latest_by': ['id']},
        ),
    ]
