# Generated by Django 2.2.9 on 2021-01-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myswsite', '0002_auto_20210109_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devtool',
            options={},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={},
        ),
    ]
